import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncDatabase1764787837924 implements MigrationInterface {
    name = 'SyncDatabase1764787837924'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP CONSTRAINT "fk_vehiculo_cliente"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "fk_servicio_cliente"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "fk_servicio_mecanico"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "fk_servicio_vehiculo"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "fk_venta_cliente"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "fk_venta_usuario"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP CONSTRAINT "fk_movimiento_producto"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP CONSTRAINT "fk_recordatorio_cliente"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP CONSTRAINT "fk_recordatorio_vehiculo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehiculos_clienteid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vehiculos_placa"`);
        await queryRunner.query(`DROP INDEX "public"."idx_servicios_clienteid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_servicios_estado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_servicios_mecanicoid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_servicios_vehiculoid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ventas_clienteid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ventas_estado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ventas_usuarioid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movimientos_kardex_productoid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movimientos_kardex_tipo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recordatorios_clienteid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recordatorios_estado"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recordatorios_fechaproxima"`);
        await queryRunner.query(`DROP INDEX "public"."idx_recordatorios_vehiculoid"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_rol_check"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "servicios_estado_check"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "ventas_estado_check"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP CONSTRAINT "movimientos_kardex_tipo_check"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP CONSTRAINT "recordatorios_estado_check"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP CONSTRAINT "recordatorios_tiporecordatorio_check"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "proximo_cambio_km"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "proximo_cambio_fecha"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "pieza_reemplazada"`);
        await queryRunner.query(`CREATE TYPE "public"."productos_tipo_enum" AS ENUM('ACEITE', 'FILTRO', 'OTRO')`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "tipo" "public"."productos_tipo_enum"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "marca" character varying`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "presentacion" character varying`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "costounitario" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "margenporcentaje" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "stockactual" integer`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "proximocambiokm" integer`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "proximocambiofecha" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "piezareemplazada" character varying`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_email_key"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "passwordhash"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "passwordhash" character varying`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "nombre" character varying`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "rol"`);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_rol_enum" AS ENUM('admin', 'owner', 'mechanic', 'recepcion')`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "rol" "public"."usuarios_rol_enum"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "activo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "creadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "creadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "actualizadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "actualizadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "nombre" character varying`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "telefono" character varying`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "direccion" character varying`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "creadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "creadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "actualizadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "actualizadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP CONSTRAINT "vehiculos_placa_key"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP COLUMN "placa"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD "placa" character varying`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD CONSTRAINT "UQ_a9455f3a37d1d922a10f51664e9" UNIQUE ("placa")`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP COLUMN "marca"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD "marca" character varying`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP COLUMN "modelo"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD "modelo" character varying`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "anio" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "kmactual" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "creadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "creadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "actualizadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "actualizadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "nombre" character varying`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "productos_sku_key"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "sku" character varying`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "precio" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "precio" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "categoria"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "categoria" character varying`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "stock" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "stock" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "creadoen"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "creadoen" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "actualizadoen"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "actualizadoen" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "detalles" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "estado"`);
        await queryRunner.query(`CREATE TYPE "public"."servicios_estado_enum" AS ENUM('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'CANCELADO')`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "estado" "public"."servicios_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "costototal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "tipo" character varying DEFAULT 'GENERAL'`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "creadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "creadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "actualizadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "actualizadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "detalles" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "estado"`);
        await queryRunner.query(`CREATE TYPE "public"."ventas_estado_enum" AS ENUM('PENDIENTE', 'COMPLETADA', 'CANCELADA')`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "estado" "public"."ventas_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "costototal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "creadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "creadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "actualizadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "actualizadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP COLUMN "tipo"`);
        await queryRunner.query(`CREATE TYPE "public"."movimientos_kardex_tipo_enum" AS ENUM('ENTRADA', 'SALIDA')`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD "tipo" "public"."movimientos_kardex_tipo_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP COLUMN "razon"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD "razon" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP COLUMN "referenciaid"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD "referenciaid" character varying`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ALTER COLUMN "creadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ALTER COLUMN "creadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "tiporecordatorio"`);
        await queryRunner.query(`CREATE TYPE "public"."recordatorios_tiporecordatorio_enum" AS ENUM('CAMBIO_ACEITE', 'MANTENIMIENTO')`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "tiporecordatorio" "public"."recordatorios_tiporecordatorio_enum"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "kmproximo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "fechaproxima"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "fechaproxima" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "estado"`);
        await queryRunner.query(`CREATE TYPE "public"."recordatorios_estado_enum" AS ENUM('PENDIENTE', 'COMPLETADO', 'CANCELADO')`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "estado" "public"."recordatorios_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "creadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "creadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "actualizadoen" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "actualizadoen" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD CONSTRAINT "FK_a5608a34f498218bffbceb66aec" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_68fbdf1734036c2eb8307415be5" FOREIGN KEY ("vehiculoid") REFERENCES "vehiculos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_0d181571019ff896e0752900a07" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_13b822c2119988fc7db4b3db7c8" FOREIGN KEY ("mecanicoid") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_c599489188de651be67c6808339" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_89c2b3729b87d8a90344df5d66b" FOREIGN KEY ("usuarioid") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD CONSTRAINT "FK_c686c0a2864d577bc4f6c4b5bc7" FOREIGN KEY ("productoid") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD CONSTRAINT "FK_d19917234603dd075972d2a2cec" FOREIGN KEY ("vehiculoid") REFERENCES "vehiculos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD CONSTRAINT "FK_774d29a8390e288fd56b5ac40a6" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP CONSTRAINT "FK_774d29a8390e288fd56b5ac40a6"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP CONSTRAINT "FK_d19917234603dd075972d2a2cec"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP CONSTRAINT "FK_c686c0a2864d577bc4f6c4b5bc7"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_89c2b3729b87d8a90344df5d66b"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_c599489188de651be67c6808339"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_13b822c2119988fc7db4b3db7c8"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_0d181571019ff896e0752900a07"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_68fbdf1734036c2eb8307415be5"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP CONSTRAINT "FK_a5608a34f498218bffbceb66aec"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "actualizadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "actualizadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "creadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "creadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "estado"`);
        await queryRunner.query(`DROP TYPE "public"."recordatorios_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "estado" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "descripcion" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "fechaproxima"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "fechaproxima" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "kmproximo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" DROP COLUMN "tiporecordatorio"`);
        await queryRunner.query(`DROP TYPE "public"."recordatorios_tiporecordatorio_enum"`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD "tiporecordatorio" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ALTER COLUMN "creadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ALTER COLUMN "creadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP COLUMN "referenciaid"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD "referenciaid" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP COLUMN "razon"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD "razon" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" DROP COLUMN "tipo"`);
        await queryRunner.query(`DROP TYPE "public"."movimientos_kardex_tipo_enum"`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD "tipo" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "actualizadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "actualizadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "creadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "creadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "costototal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP COLUMN "estado"`);
        await queryRunner.query(`DROP TYPE "public"."ventas_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD "estado" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "detalles" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ventas" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "actualizadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "actualizadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "creadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "creadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "tipo"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "tipo" character varying(50) DEFAULT 'GENERAL'`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "costototal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "estado"`);
        await queryRunner.query(`DROP TYPE "public"."servicios_estado_enum"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "estado" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "detalles" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "descripcion" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "actualizadoen"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "actualizadoen" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "creadoen"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "creadoen" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "stock" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "stock" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "categoria"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "categoria" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "precio" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "precio" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "sku" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "productos_sku_key" UNIQUE ("sku")`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "productos" ADD "nombre" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productos" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "actualizadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "actualizadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "creadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "creadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "kmactual" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "anio" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP COLUMN "modelo"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD "modelo" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP COLUMN "marca"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD "marca" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP CONSTRAINT "UQ_a9455f3a37d1d922a10f51664e9"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" DROP COLUMN "placa"`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD "placa" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD CONSTRAINT "vehiculos_placa_key" UNIQUE ("placa")`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "actualizadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "actualizadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "creadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "creadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "direccion" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "telefono" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD "nombre" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "actualizadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "actualizadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "creadoen" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "creadoen" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "activo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "rol"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_rol_enum"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "rol" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "nombre" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "passwordhash"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "passwordhash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "piezareemplazada"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "proximocambiofecha"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "proximocambiokm"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "stockactual"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "margenporcentaje"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "costounitario"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "presentacion"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "marca"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP COLUMN "tipo"`);
        await queryRunner.query(`DROP TYPE "public"."productos_tipo_enum"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "pieza_reemplazada" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "proximo_cambio_fecha" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD "proximo_cambio_km" integer`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "passwordHash" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD CONSTRAINT "recordatorios_tiporecordatorio_check" CHECK (((tiporecordatorio)::text = ANY (ARRAY[('CAMBIO_ACEITE'::character varying)::text, ('MANTENIMIENTO'::character varying)::text])))`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD CONSTRAINT "recordatorios_estado_check" CHECK (((estado)::text = ANY (ARRAY[('PENDIENTE'::character varying)::text, ('COMPLETADO'::character varying)::text, ('CANCELADO'::character varying)::text])))`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD CONSTRAINT "movimientos_kardex_tipo_check" CHECK (((tipo)::text = ANY (ARRAY[('ENTRADA'::character varying)::text, ('SALIDA'::character varying)::text])))`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "ventas_estado_check" CHECK (((estado)::text = ANY (ARRAY[('PENDIENTE'::character varying)::text, ('COMPLETADA'::character varying)::text, ('CANCELADA'::character varying)::text])))`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "servicios_estado_check" CHECK (((estado)::text = ANY (ARRAY[('PENDIENTE'::character varying)::text, ('EN_PROCESO'::character varying)::text, ('COMPLETADO'::character varying)::text, ('CANCELADO'::character varying)::text])))`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_rol_check" CHECK (((rol)::text = ANY (ARRAY[('admin'::character varying)::text, ('owner'::character varying)::text, ('mechanic'::character varying)::text, ('recepcion'::character varying)::text])))`);
        await queryRunner.query(`CREATE INDEX "idx_recordatorios_vehiculoid" ON "recordatorios" ("vehiculoid") `);
        await queryRunner.query(`CREATE INDEX "idx_recordatorios_fechaproxima" ON "recordatorios" ("fechaproxima") `);
        await queryRunner.query(`CREATE INDEX "idx_recordatorios_estado" ON "recordatorios" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_recordatorios_clienteid" ON "recordatorios" ("clienteid") `);
        await queryRunner.query(`CREATE INDEX "idx_movimientos_kardex_tipo" ON "movimientos_kardex" ("tipo") `);
        await queryRunner.query(`CREATE INDEX "idx_movimientos_kardex_productoid" ON "movimientos_kardex" ("productoid") `);
        await queryRunner.query(`CREATE INDEX "idx_ventas_usuarioid" ON "ventas" ("usuarioid") `);
        await queryRunner.query(`CREATE INDEX "idx_ventas_estado" ON "ventas" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_ventas_clienteid" ON "ventas" ("clienteid") `);
        await queryRunner.query(`CREATE INDEX "idx_servicios_vehiculoid" ON "servicios" ("vehiculoid") `);
        await queryRunner.query(`CREATE INDEX "idx_servicios_mecanicoid" ON "servicios" ("mecanicoid") `);
        await queryRunner.query(`CREATE INDEX "idx_servicios_estado" ON "servicios" ("estado") `);
        await queryRunner.query(`CREATE INDEX "idx_servicios_clienteid" ON "servicios" ("clienteid") `);
        await queryRunner.query(`CREATE INDEX "idx_vehiculos_placa" ON "vehiculos" ("placa") `);
        await queryRunner.query(`CREATE INDEX "idx_vehiculos_clienteid" ON "vehiculos" ("clienteid") `);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD CONSTRAINT "fk_recordatorio_vehiculo" FOREIGN KEY ("vehiculoid") REFERENCES "vehiculos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recordatorios" ADD CONSTRAINT "fk_recordatorio_cliente" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_kardex" ADD CONSTRAINT "fk_movimiento_producto" FOREIGN KEY ("productoid") REFERENCES "productos"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "fk_venta_usuario" FOREIGN KEY ("usuarioid") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "fk_venta_cliente" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "fk_servicio_vehiculo" FOREIGN KEY ("vehiculoid") REFERENCES "vehiculos"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "fk_servicio_mecanico" FOREIGN KEY ("mecanicoid") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "fk_servicio_cliente" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehiculos" ADD CONSTRAINT "fk_vehiculo_cliente" FOREIGN KEY ("clienteid") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
